FORMAT: 1A

# Notes API
Notes API is a *short texts saving* service similar to its physical paper presence on your table.

# Group Notes
Notes related resources of the **Notes API**

## Notes [/publish/publishing/{publishingId}/notes]
    
    + Attributes (object)
      + id: ioqwe909wwqm9DD (string)
      + message: functional test note (string)
      + created: (object)
        + authorId: me (string)
        + date: 2015-04-19T09:28:07.984Z (string) - time stamp
    
### List all Publishing Notes [GET]
+ Response 200 (application/json)

        + Attributes (array[Notes])

### Create a Publishing Note [POST]
+ Request (application/json)

        {
           "message": "some message"                    // required
        }

+ Response 201 (application/json)

        {
            "id": "ASD9ASD989873A898ADS",
            "message": "functional test note"              
        }

## Publishing Note [/publish/publishing/{publishingId}/notes/{id}]

### Remove a Publishing Note [DELETE]
+ Response 204
