FORMAT: 1A

# Publish API

# Group Publishing Notes
Notes resources

## Note [/publish/publishing/{publishingId}/notes/{id}]

+ Parameters
    + id (string, required)
    
+ Attributes
    + id: ASD9ASD989873A898ADS (string, required)
    + message: functional test note (string, required)
    + authorId: 11223ASD (string, required)
    + date: `2015-04-19T09:28:07.984Z` (string, required) - format: yyyy-MM-ddThh:mm:ss[.sss]Z

### Remove a Publishing Note [DELETE]

+ Request (application/json)
    
    + Headers
            
            X-Falcon-Session: sessionId

+ Response 204

## Notes [/publish/publishing/{publishingId}/notes]
### List all Publishing Notes [GET]

+ Response 200 (application/json)

        [{
             "id": "ASD9ASD989873A898ADS",
             "message": "functional test note",
             "created": {
                 "authorId": "QEQWE31312DDFG",
                 "date": "2015-04-19T09:28:07.984Z"
             }   
        }]

### Create a Publishing Note [POST]

+ Attributes (object)
    + message: some message (string, required)

+ Request (application/json)

+ Response 201 (application/json)

        {
            "id": "ASD9ASD989873A898ADS",
            "message": "some message"              
        }