FORMAT: 1A

# Notes API
Notes API is a *short texts saving* service similar to its physical paper presence on your table.

# Group Notes
Notes related resources of the **Notes API**

## Publishing Notes Collection [/publish/publishing/{publishingId}/notes]
### List all Publishing Notes [GET]
+ Response 200 (application/json)

        [{
             "id": "",
             "message": "functional test note",
             "created": {
                 "authorId": "",
                 "date": "2015-04-19T09:28:07.984Z"
             }   
        }]

### Create a Publishing Note [POST]

+ Attributes (object)
    + message: some message (string, required)

+ Request (application/json)

+ Response 201 (application/json)

        {
            "id": "ASD9ASD989873A898ADS",
            "message": "some message"              
        }

## Remove [/publish/publishing/{publishingId}/notes/{id}]
### Remove a Publishing Note [DELETE]
+ Response 204